CREATE TABLE IF NOT EXISTS fact.fact_online_sales (
    order_key           VARCHAR(10)   NOT NULL,
    order_line_number   SMALLINT      NOT NULL,
    customer_key        BIGINT,
    product_key         INTEGER       NOT NULL,
    sales_territory_key SMALLINT,
    channel_key         SMALLINT      NOT NULL DEFAULT 1,
    payment_method_key  SMALLINT,
    delivery_method_key SMALLINT,
    order_date_key      INTEGER       NOT NULL,
    ship_date_key       INTEGER,
    quantity            SMALLINT      NOT NULL,
    catalog_price       NUMERIC(7,2)  NOT NULL,
    discount_amount     NUMERIC(7,2)  NOT NULL DEFAULT 0,
    discount_pctg       SMALLINT      NOT NULL DEFAULT 0,
    transaction_price   NUMERIC(7,2)  NOT NULL,
    delivery_cost       NUMERIC(7,2),
    product_cost        NUMERIC(8,2),
    CONSTRAINT pk_fact_online_sales PRIMARY KEY (order_key, order_line_number)
);
